# syntax=docker/dockerfile:experimental

# syntax=docker/dockerfile:1
# Use ubuntu 20.04 as base image for arm64
FROM --platform=linux/arm64 ubuntu:20.04
# FROM ubuntu:20.04

# Define the folder /code as the main working directory
WORKDIR /code

# ===============================
# Install Python3.10 
# ===============================
# Install python3.10. Since ubuntu 20.04 only has python3.8 by default, we need to add some addtional ppa's to install python3.10
RUN apt-get update && apt install -y software-properties-common
# Add deadsnakes ppa which contains python3.10 for ubuntu 20.04
RUN add-apt-repository -y ppa:deadsnakes/ppa
# Install python3.10
RUN apt update && apt install -y python3.10 python3.10-distutils python3.10-dev python3.10-minimal
# Make sure python and python3 point to python3.10, and not the system default python3.8
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

# ===============================
# Install common dependencies
# ===============================
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    wget \
    ccache \
    assimp-utils \
    build-essential \
    cmake \
    git \
    libboost-all-dev \
    libccd-dev \
    libeigen3-dev \
    libglew-dev \
    software-properties-common \
    net-tools \
    virtualenv \
    wget \
    patchelf \
    apt-transport-https \
    liblapack-dev \
    libopenblas-dev \
    libhdf5-dev \
    libc6 \
    libgomp1 \
    libglfw3 \
    xvfb \
    x11vnc \ 
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# ===============================
# Install Python dependencies
# Specified in the requirements.txt file
# ===============================
# Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python get-pip.py
RUN rm get-pip.py

# This is to make sure the newest version of cffi is installed (for some reason it will install 1.14.0, which is an old version).
RUN pip install --upgrade pip setuptools 

# Install dependencies and PyTorch
RUN pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cpu

# Copy the current directory contents into the container at /code
# COPY . .

# Install dependencies and the package in editable mode
RUN pip install --upgrade pip
# RUN pip install -e .

COPY .setup .setup
# Compile and install acados
RUN ./.setup/ubuntu/install_acados.sh
RUN ./.setup/ubuntu/install_casadi.sh
ENV ACADOS_SOURCE_DIR="/acados"
ENV LD_LIBRARY_PATH="/acados/lib:$LD_LIBRARY_PATH"


# Compile and install l4acados
# COPY .setup/ubuntu/install_l4acados.sh .setup/ubuntu/install_l4acados.sh
# RUN ./.setup/ubuntu/install_l4acados.sh
# ENV ACADOS_SOURCE_DIR="l4acados/external/acados"
# ENV LD_LIBRARY_PATH="$ACADOS_SOURCE_DIR/lib"

# Setup the Tera renderer on Arm machines
RUN ./.setup/ubuntu/install_tera_renderer.sh

# ENV LD_PRELOAD="/usr/local/lib/python3.10/dist-packages/torch.libs/libgomp-f3febf51.so.1.0.0 /lib/aarch64-linux-gnu/libGLdispatch.so.0"
# ENV MUJOCO_GL=glfw

# # ==== Voxel Only
# # ENV DISPLAY=""

# # Local PC
# ENV DISPLAY=""

# # Expose ports for UDP
# EXPOSE 5005/udp
# EXPOSE 5006/udp
