from typing import Mapping


def build_wandb_policy_training_payload(
    *,
    phase_name: str,
    phase_epoch: int,
    global_epoch: int,
    critic_grad_scale: float,
    actor_loss_mean: float,
    critic_loss_mean: float,
    true_kl_mean: float,
    clip_fraction: float,
    explained_variance: float,
    return_std: float,
    value_std: float,
    critic_loss_normalized: float,
    mean_std: float,
    mean_log_std: float,
    mean_episodic_returns: float,
    success_env_count: float,
    success_rate: float,
    terminated_step_count: float,
    success_termination_step_count: float,
    failure_termination_step_count: float,
    success_termination_env_rate: float,
    failure_termination_env_rate: float,
    terminal_envs_at_end: float,
    terminal_env_rate_at_end: float,
    mean_lateral_error: float,
    mean_angle_error: float,
    mean_final_position_error: float,
    current_failure_fraction: float,
    current_disturbance_fraction: float,
    current_difficulty_bin: int,
    median_final_position_error: float,
    p75_final_position_error: float,
    p90_final_position_error: float,
    fraction_pos_within_radius: float,
    fraction_speed_within_limit: float,
    fraction_att_within_limit: float,
    fraction_ang_speed_within_limit: float,
    fraction_all_conditions_except_hold: float,
    mean_consecutive_success_hold_steps: float,
    reward_component_means: Mapping[str, float],
    reward_scale_metrics: Mapping[str, float],
) -> dict[str, float | int | str]:
    reward_payload = {
        f"reward_components/{metric_name}": float(metric_value)
        for metric_name, metric_value in reward_component_means.items()
    }
    reward_scale_payload = {
        f"reward_scale/{metric_name}": float(metric_value)
        for metric_name, metric_value in reward_scale_metrics.items()
    }
    return {
        "curriculum/phase": phase_name,
        "curriculum/phase_epoch": phase_epoch,
        "curriculum/global_epoch": global_epoch,
        "curriculum/critic_grad_scale": critic_grad_scale,
        "curriculum/failure_fraction": current_failure_fraction,
        "curriculum/disturbance_fraction": current_disturbance_fraction,
        "curriculum/difficulty_bin": current_difficulty_bin,
        "training_health/true_kl_mean": true_kl_mean,
        "training_health/explained_variance": explained_variance,
        "policy_stats/mean_std": mean_std,
        "objective/train_mean_episodic_return": mean_episodic_returns,
        "task_performance/success_rate": success_rate,
        "task_performance/mean_lateral_error": mean_lateral_error,
        "task_performance/mean_angle_error": mean_angle_error,
        "task_performance/mean_final_position_error": mean_final_position_error,
        "task_performance/median_final_position_error": median_final_position_error,
        "task_performance/p75_final_position_error": p75_final_position_error,
        "task_performance/p90_final_position_error": p90_final_position_error,
        "task_performance/fraction_pos_within_radius": fraction_pos_within_radius,
        "task_performance/fraction_speed_within_limit": fraction_speed_within_limit,
        "task_performance/fraction_att_within_limit": fraction_att_within_limit,
        "task_performance/fraction_ang_speed_within_limit": fraction_ang_speed_within_limit,
        "task_performance/fraction_all_conditions_except_hold": fraction_all_conditions_except_hold,
        "task_performance/mean_consecutive_success_hold_steps": mean_consecutive_success_hold_steps,
        **reward_payload,
        **reward_scale_payload,
    }


def build_logger_policy_training_payload(
    *,
    phase_name: str,
    phase_epoch: int,
    critic_grad_scale: float,
    actor_loss_mean: float,
    critic_loss_mean: float,
    true_kl_mean: float,
    clip_fraction: float,
    explained_variance: float,
    return_std: float,
    value_std: float,
    critic_loss_normalized: float,
    success_env_count: float,
    success_rate: float,
    terminated_step_count: float,
    success_termination_step_count: float,
    failure_termination_step_count: float,
    success_termination_env_rate: float,
    failure_termination_env_rate: float,
    terminal_envs_at_end: float,
    terminal_env_rate_at_end: float,
    mean_std: float,
    mean_lateral_error: float,
    mean_angle_error: float,
    mean_final_position_error: float,
    current_failure_fraction: float,
    current_disturbance_fraction: float,
    current_difficulty_bin: int,
    median_final_position_error: float,
    p75_final_position_error: float,
    p90_final_position_error: float,
    fraction_pos_within_radius: float,
    fraction_speed_within_limit: float,
    fraction_att_within_limit: float,
    fraction_ang_speed_within_limit: float,
    fraction_all_conditions_except_hold: float,
    mean_consecutive_success_hold_steps: float,
    train_mean_episodic_returns: float,
    reward_scale_metrics: Mapping[str, float],
) -> dict[str, float | int | str]:
    return {
        "phase": phase_name,
        "phase_epoch": phase_epoch,
        "critic_grad_scale": critic_grad_scale,
        "failure_fraction": current_failure_fraction,
        "disturbance_fraction": current_disturbance_fraction,
        "difficulty_bin": current_difficulty_bin,
        "actor_loss_mean": actor_loss_mean,
        "critic_loss_mean": critic_loss_mean,
        "true_kl_mean": true_kl_mean,
        "clip_fraction": clip_fraction,
        "explained_variance": explained_variance,
        "return_std": return_std,
        "value_std": value_std,
        "critic_loss_normalized": critic_loss_normalized,
        "success_env_count": success_env_count,
        "success_rate": success_rate,
        "terminated_step_count": terminated_step_count,
        "success_termination_step_count": success_termination_step_count,
        "failure_termination_step_count": failure_termination_step_count,
        "success_termination_env_rate": success_termination_env_rate,
        "failure_termination_env_rate": failure_termination_env_rate,
        "terminal_envs_at_end": terminal_envs_at_end,
        "terminal_env_rate_at_end": terminal_env_rate_at_end,
        "mean_std": mean_std,
        "mean_lateral_error": mean_lateral_error,
        "mean_angle_error": mean_angle_error,
        "mean_final_position_error": mean_final_position_error,
        "median_final_position_error": median_final_position_error,
        "p75_final_position_error": p75_final_position_error,
        "p90_final_position_error": p90_final_position_error,
        "fraction_pos_within_radius": fraction_pos_within_radius,
        "fraction_speed_within_limit": fraction_speed_within_limit,
        "fraction_att_within_limit": fraction_att_within_limit,
        "fraction_ang_speed_within_limit": fraction_ang_speed_within_limit,
        "fraction_all_conditions_except_hold": fraction_all_conditions_except_hold,
        "mean_consecutive_success_hold_steps": mean_consecutive_success_hold_steps,
        "train_mean_episodic_returns": train_mean_episodic_returns,
        **{f"reward_scale_{k}": float(v) for k, v in reward_scale_metrics.items()},
    }
